export const wordList = [
  "Ciplox  Ciprofloxacin (500mg, 1 tab twice daily, oral, after food)",
  "Ciplox  Ciprofloxacin (250mg, 1 tab twice daily, oral, after food)",
  "Roxid Roxithromycin (150mg, 1 tab twice daily, oral, after food)",
  "Moxiflox Moxifloxacin (400mg, 1 tab once daily, oral, after food)",
  "Levoflox Levofloxacin (500mg, 1 tab once daily, oral, after food)",
  "Augmentin duo 1g  Amoxycillin 875mg +Clavulinic acid 125mg (1g, 1 tab twice daily, oral, after food)",
  "Augmentin duo  Amoxycillin 500mg +Clavulinic acid 125mg (625mg, 1 tab twice daily, oral, after food)",
  "Augmentin DDS (Amoxycillin 400mg +Clavulinic acid 57mg) / 5 ml (457mg, 5 ml twice daily, oral, after food)",
  "Augmentin  (Amoxycillin 200mg +Clavulinic acid 28mg) /5ml (228mg, 5 ml twice daily, oral, after food)",
  "Cepodem Cefpodoxime (200mg, 1 tab twice daily, oral, after food)",
  "Cepodem Cefpodoxime (100mg, 1 tab twice daily, oral, after food)",
  "Cepodem Cefpodoxime 50mg/5ml (5 ml twice daily, oral, after food)",
  "Pulmocef Cefuroxime (500mg, 1 tab twice daily, oral, after food)",
  "Pulmocef Cefuroxime (250mg, 1 tab twice daily, oral, after food)",
  "Microdox-LBX Doxycyclin + Lactobacilli (100mg, 1 Cap twice daily, oral, after food)",
  "Claribid  Clarithromycin (250mg, 1 tab twice daily, oral, after food)",
  "Altacef Cefuroxime 125mg/5ml (5 ml twice daily, oral, after food)",
  "Forcan Fluconazole (400mg, 1 tab stat, oral, after food)",
  "Signoflam Aceclofenac 100mg +Paracetamol 325mg+ serratiopeptidase 15mg (1 tab twice daily, oral, after food)",
  "Zerodol P Aceclofenac100mg +Paracetamol 325mg (1 tab twice daily, oral, after food)",
  "Meftal P Mafenamic acid 100mg/5ml (5 ml twice daily, oral, after food)",
  "Calpol paracetamol 650mg (1 tab thrice daily, oral, after food)",
  "Calpol paracetamol 500mg (1 tab thrice daily, oral, after food)",
  "Calpol paracetamol 250mg/5ml (5 ml thrice daily, oral, after food)",
  "Combiflam Ibuprofen 400mg + paracetamol 325mg (1 tab thrice daily, oral, after food)",
  "Ibugesic Plus (Ibuprofen 100mg + paracetamol 162.5)/5ml (5 ml thrice daily, oral, after food)",
  "Ugesic  Piroxicam 20mg (2 tab stat on day 1, then once daily , oral, after food)",
  "chymoral forte  Trypsin-chymotrypsin 1L AU (1 tab thrice daily, oral, after food)",
  "Zerodol TH 4 Aceclofenac 100mg + Thiocolchicocide 4mg (1 tab twice daily, oral, after food)",
  "Betnesol Betamethasone (0.5 mg, 1 tab twice daily, oral, after food)",
  "Betnesol forte Betamethasone (1mg, 1 tab twice daily, oral, after food)",
  "Omnacortil oral drops Prednisolone 5mg/ml (4 drops twice daily, oral, after food)",
  "Defcort Deflazacort (1 tab twice daily, oral, after food)",
  "Ebast Ebastine (20mg, 1 tab once daily, oral, after food in evening)",
  "EbastM Ebastine+Montelukast (10mg+10mg, 1 tab once daily, oral, after food in evening)",
  "Montair LC kid Levocetrizine 2.5mg/5ml+ Montelukast 4mg/5ml (5ml once daily, oral, after food in evening)",
  "Montair Montelukast (10mg , 1 tab once daily, oral, after food)",
  "Alerid  cetrizine (10mg, 1 tab once daily, oral, after food in evening)",
  "Atarax Hydroxyzosine 25mg (2 tab once daily, oral, 8:00PM)",
  "Phenargan Promethazine 5mg/5ml (2.5 ml once daily, oral, 8:00PM)",
  "Alerid Cetrizine 5mg/5ml (2.5 ml once daily, oral, after food)",
  "Montair FX montelukast 10+Fexofenadine 120 (1 tab once daily, oral, after food)",
  "Lorfast meltab  Loratidine (10mg, 1 tab once daily, oral, after food)",
  "Relent Cetrizine+Ambroxol (5mg+60mg, 1 tab once daily, oral, after food)",
  "Raciper esomeprazole (20mg, 1 tab once daily, oral, empty stomach)",
  "Raciper Plus SR esomeprazole 40mg + Levosulpiride 75mg",
  "Ulgel A sugarfree Megaldrate 540mg + Simethicon50mg + oxetacaine 10mg ",
  "Supradyn daily multivitamin",
  "CCM Cacium citrate maleate 250mg, vitaminD3 100IU, Folic Acid 50mcg",
  "FDC D3 chewable Cholecalciferol 60k IU",
  "Limcee 500mg Ascorbic acid ",
  "Becosule Z ",
  "Evion 200mg Tocopheryl acetate ",
  "Irex Sodium feredetate 231mg, Folic acid, Vitamin B12 ",
  "Livogen kids  Sodium feredetate 231mg ",
  "A-Z multivitamin and multimineral ",
  "Cobadex CZS Nutritional supplement ",
  "Liquid Paraffin nasal drops",
  "Otrinoz adult drops xylometazoline 1% ",
  "Otrinoz Paediatric drops xylometazoline 0.5% ",
  "Phensedyl LR oral susp levocloperastine 20mg/5ml ",
  "Ventorlin  Salbutamol 2mg/5ml",
  "Macberry (Dextromethorphan 10mg +Ambroxol 15mg +phenyleherine 5 mg +Chlorpheniramine 2mg +menthol)/5ml",
  "Zedex (chlorpheniramine 2mg +Dextromethorphan 10mg)/5ml ",
  "Macberry-LS SF (Guaifenesin 50mg +Levosalbutamol 1mg+Ambroxol 30mg)/5ml",
  "Relent + (Cetrizine 5mg +Ambroxol 30mg)/5ml ",
  "Ciplox D ear drops Ciprofloxacin0.3% +Dexamethasone 0.1% ",
  "Waxolve eardrops Benzocaine+chlorbutol+turpentine oil+paradichlorobenzene",
  "Otofungin F ear drops Fluconazole 0.3% ",
  "Otocil HC ear drops Hydrocortisone 1% +Acetic Acid 2%",
  "Otogon ear drops Lidocaine 1% +Phenazone 4% ",
  "Candid ear drops Lidocaine 2%+Clotrimazole 1% ",
  "Candibiotic ear drops Beclometasone+Neomycin + Clotrimazole 1% ",
  "Lobate GM cream ",
  "Neosporin H oint ",
  "phensedyl LR ",
  "Tossex XP ",
  "Abphylline 200mg SR Acebrophylline ",
  "Azee 250mg Azithromycin ",
  "Oflox 200 ofloxacin ",
  "Oflox 100 ofloxacin ",
  "Oflox 50mg/5ml Ofloxacin ",
  "Sinarest chlorpheniramine 2mg +paracetamol 500mg +phenylepherine 10mg ",
  "Maxtra (chlorpheniramine 2mg +phenylepherine 5mg)/5ml ",
  "Maxtra P (chlorpheniramine 1mg +paracetamol 125mg +phenylepherine 5mg)/5ml ",
  "maxtra gargles benzydamine 0.15% ",
  "betadine gargles povidone iodine 2% ",
  "Avamys nasal spray Fluticasone furoate 0.05% ",
  "Metaspray nasal spray Mometasone 50mcg ",
  "Duonase nasal spray fluticasone propionate + Azelastine ",
  "Nasowash nasal rinse  ",
  "Nasoclear nasal drops ",
  "Biostar gold antioxidant, ALA 100mg, Lycopene 5mg, vitamins and minerals ",
  "Candid mouth paint clotrimazole 1% ",
  "Kenacort new 0.1% buccal paste Triamcinolone ",
  "Dologel CT oral gel choline salicylate + Lidocaine ",
  "Vizylac pre and probiotic ",
  "Metrogyl 400 mg Metronidazole ",
  "Metrogyl 200 mg Metronidazole "
];