export const wordList = [
  "Tab", "Ciplox", "Ciprofloxacin", "Roxid", "Roxithromycin", "Moxiflox", "Moxifloxacin", "Levoflox",
  "Levofloxacin", "Augmentin", "duo", "1g", "Amoxycillin", "875mg", "Clavulinic", "acid", "125mg",
  "500mg", "DDS", "400mg", "57mg", "5", "ml", "200mg", "28mg", "Cepodem", "Cefpodoxime", "50mg",
  "Pulmocef", "Cefuroxime", "Microdox-LBX", "Doxycyclin", "Lactobacilli", "Claribid", "Clarithromycin",
  "Altacef", "125mg", "Forcan", "Fluconazole", "Signoflam", "Aceclofenac", "100mg", "Paracetamol",
  "325mg", "serratiopeptidase", "15mg", "Zerodol", "P", "Meftal", "Mafenamic", "Calpol", "650mg",
  "Susp", "250mg", "Combiflam", "Ibuprofen", "Ibugesic", "Plus", "162.5", "Ugesic", "Piroxicam",
  "20mg", "chymoral", "forte", "Trypsin-chymotrypsin", "1L", "AU", "TH", "Thiocolchicocide", "4mg",
  "Betnesol", "forte", "Omnacortil", "oral", "drops", "Prednisolone", "5mg/ml", "Defcort", "Deflazacort",
  "Ebast", "Ebastine", "EbastM", "Montelukast", "Syp", "Montair", "LC", "kid", "Levocetrizine",
  "2.5mg/5ml", "4mg/5ml", "Alerid", "cetrizine", "Atarax", "Hydroxyzosine", "25mg", "Phenargan",
  "Promethazine", "5mg/5ml", "Cetrizine", "Montair", "FX", "10", "Fexofenadine", "120", "Lorfast",
  "meltab", "Loratidine", "Relent", "Ambroxol", "Raciper", "esomeprazole", "Cap", "SR", "40mg",
  "Levosulpiride", "75mg", "Ulgel", "A", "sugarfree", "Megaldrate", "540mg", "Simethicon50mg",
  "oxetacaine", "10mg", "Supradyn", "daily", "multivitamin", "CCM", "Cacium", "citrate", "maleate",
  "vitaminD3", "100IU", "Folic", "Acid", "50mcg", "FDC", "D3", "chewable", "Cholecalciferol", "60k",
  "IU", "Limcee", "Ascorbic", "Becosule", "Z", "Evion", "Tocopheryl", "acetate", "Irex", "Sodium",
  "feredetate", "231mg", "Vitamin", "B12", "Livogen", "kids", "A-Z", "multimineral", "Cobadex",
  "CZS", "Nutritional", "supplement", "Liquid", "Paraffin", "nasal", "Otrinoz", "adult", "xylometazoline",
  "1%", "Paediatric", "0.5%", "Phensedyl", "LR", "oral", "levocloperastine", "20mg/5ml", "Ventorlin",
  "Salbutamol", "2mg/5ml", "Macberry", "Dextromethorphan", "10mg", "phenyleherine", "5", "Chlorpheniramine",
  "2mg", "menthol", "Zedex", "Macberry-LS", "SF", "Guaifenesin", "50mg", "Levosalbutamol", "1mg",
  "Relent", "Ciplox", "D", "ear", "Dexamethasone", "0.3%", "Waxolve", "Benzocaine", "chlorbutol",
  "turpentine", "oil", "paradichlorobenzene", "Otofungin", "F", "Fluconazole", "Otocil", "HC", "Hydrocortisone",
  "1%", "Acetic", "Otogon", "Lidocaine", "Phenazone", "Candid", "Clotrimazole", "Candibiotic", "Beclometasone",
  "Neomycin", "Lobate", "GM", "cream", "Neosporin", "H", "ointment", "Tossex", "XP", "Abphylline",
  "Acebrophylline", "Azee", "250mg", "Azithromycin", "Oflox", "200", "ofloxacin", "100", "Sinarest",
  "phenylepherine", "10mg", "Maxtra", "5mg", "Maxtra", "P", "125mg", "gargles", "benzydamine", "0.15%",
  "betadine", "povidone", "iodine", "2%", "Avamys", "Fluticasone", "furoate", "0.05%", "Metaspray",
  "Mometasone", "50mcg", "Duonase", "propionate", "Azelastine", "Nasowash", "rinse", "Nasoclear",
  "Biostar", "gold", "antioxidant", "ALA", "100mg", "Lycopene", "5mg", "Kenacort", "new", "0.1%",
  "buccal", "paste", "Triamcinolone", "Dologel", "CT", "oral", "gel", "choline", "salicylate", "Vizylac",
  "pre", "probiotic", "Metrogyl", "400", "mg", "Metronidazole", "200"
];
